// <auto-generated />
namespace QuanLyNhanSu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class delete_ghichu_chamcong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_ghichu_chamcong));
        
        string IMigrationMetadata.Id
        {
            get { return "202006261754004_delete_ghichu_chamcong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
